name: hlaw
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.4
  firebase_core:
  firebase_auth:
  cloud_firestore:
  fluttertoast: ^8.2.4
  uuid:
  agora_rtc_engine: ^5.0.0
  permission_handler:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: KantumruyPro
      fonts:
        - asset: assets/font/KantumruyPro-Bold.ttf
        - asset: assets/font/KantumruyPro-BoldItalic.ttf
        - asset: assets/font/KantumruyPro-ExtraLight.ttf
        - asset: assets/font/KantumruyPro-Light.ttf
        - asset: assets/font/KantumruyPro-Italic.ttf
        - asset: assets/font/KantumruyPro-LightItalic.ttf
        - asset: assets/font/KantumruyPro-Medium.ttf
        - asset: assets/font/KantumruyPro-MediumItalic.ttf
        - asset: assets/font/KantumruyPro-Regular.ttf
        - asset: assets/font/KantumruyPro-SemiBold.ttf
        - asset: assets/font/KantumruyPro-SemiBoldItalic.ttf
        - asset: assets/font/KantumruyPro-Thin.ttf
        - asset: assets/font/KantumruyPro-ThinItalic.ttf

